export const putovanja = [
    {
        sifra: 1,
        naziv: 'Putovanje u Pariz',
        destinacija: 'Pariz',
        drzava: 'Francuska',
        datumPolaska: '2026-10-15',
        datumPovratka: '2026-10-20',
        budzet: 1200,
    },
    {
        sifra: 2,
        naziv: 'Putovanje u Rim',
        destinacija: 'Rim',
        drzava: 'Italija',
        datumPolaska: '2026-11-10',
        datumPovratka: '2026-11-15',
        budzet: 1000,
    },
    {
        sifra: 3,
        naziv: 'Putovanje u Tokio',
        destinacija: 'Tokio',
        drzava: 'Japan',
        datumPolaska: '2027-03-20',
        datumPovratka: '2027-03-30',
        budzet: 1800,
    },
    {
        sifra: 4,
        naziv: 'Putovanje u New York',
        destinacija: 'New York',
        drzava: 'Sjedinjene Američke Države',
        datumPolaska: '2026-12-23',
        datumPovratka: '2027-01-03',
        budzet: 4000
    },
    {
        sifra: 5,
        naziv: 'Putovanje u Amsterdam',
        destinacija: 'Amsterdam',
        drzava: 'Nizozemska',
        datumPolaska: '2027-05-01',
        datumPovratka: '2027-05-07',
        budzet: 2000,
    },
    {
        sifra: 6, 
        naziv: 'Putovanje u Barcelonu',
        destinacija: 'Barcelona',
        drzava: 'Španjolska',
        datumPolaska: '2027-06-15',
        datumPovratka: '2027-06-22',
        budzet: 1500,
    },
    {
        sifra: 7, 
        naziv: 'Putovanje u Oslo',
        destinacija: 'Oslo',
        drzava: 'Norveška',
        datumPolaska: '2026-12-12',
        datumPovratka: '2026-12-22',
        budzet: 2300,
    }
]